title:     "Troy Goode"
url:       http://www.squaredroot.com
author:
  name:    "Troy Goode"
  email:   "troygoode@gmail.com"
markdown:  redcarpet
permalink: pretty
pygments:  true
paginate:  1
exclude:   ['ARCHIVE']
