title:        Lanetix
tagline:      "Lanetix Product Development Blog"
url:          http://lanetix.github.io
author:
  name:       "Lanetix"
  email:      "info@lanetix.com"
markdown:     redcarpet
permalink:    pretty
pygments:     true
paginate:     5
